# Generated by Django 5.2 on 2025-07-18 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='website',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='Местоположение (Город, Адрес)'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_images/', verbose_name='Изображение')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.restaurant')),
            ],
        ),
    ]
