# Generated by Django 5.2 on 2025-07-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_address_remove_restaurant_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(default='18:00:00', verbose_name='Время закрытия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(default='18:00:00', verbose_name='Время открытия'),
            preserve_default=False,
        ),
    ]
