# Generated by Django 5.2.4 on 2025-07-25 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Клиент'), ('restaurant_admin', 'Администратор ресторана'), ('super_admin', 'Суперадминистратор')], default='customer', max_length=50, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен подтверждения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
