# Generated by Django 5.2 on 2025-07-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='table_images/', verbose_name='Фото стола'),
        ),
    ]
