name: Django CI/CD Pipeline

on:
  push:
    branches:
      - develop_1

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

      redis:
        image: redis:7-alpine
        ports:
          - "6379:6379"

    env:
      POSTGRES_DB_NAME: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      REDIS_URL: redis://redis:6379/0

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up database
      working-directory: .
      run: python manage.py migrate
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    - name: Run tests
      working-directory: .
      run: python manage.py test --noinput
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server host key to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Copy project files to server
      run: |
        echo "Copying project files to server..."
        export RSYNC_RSH="ssh -o StrictHostKeyChecking=no"
        rsync -avz --delete \
          --exclude '__pycache__' \
          --exclude '.env*' \
          --exclude '.git' \
          --exclude 'venv' \
          . ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}
        echo "Files copied."

    - name: Install dependencies, apply migrations, collect static files
      run: |
        echo "Executing commands on server..."
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e
          set -x
          
          echo "Changing directory to deployment folder..."
          export DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}"
          export POSTGRES_USER="postgres"
          export POSTGRES_PASSWORD="password"
          export POSTGRES_DB="testdb"
          export EMAIL_HOST_PASSWORD="${{ secrets.EMAIL_HOST_PASSWORD }}"
          export REDIS_URL="redis://localhost:6379/0"

          PROJECT_DIR="${{ secrets.DEPLOY_DIR }}"
          cd "$PROJECT_DIR"

          echo "Setting up virtual environment..."
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          
          echo "Activating virtual environment..."
          source venv/bin/activate

          echo "Installing project dependencies..."
          pip install --upgrade pip
          pip install -r requirements.txt

          echo "Creating production environment file..."
          cat > .env.prod <<EOL
        DEBUG=False
        SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        POSTGRES_DB_NAME=testdb
        POSTGRES_USER=postgres
        POSTGRES_PASSWORD=password
        POSTGRES_HOST=localhost
        POSTGRES_PORT=5432
        REDIS_HOST=localhost
        REDIS_PORT=6379
        EMAIL_HOST_USER=Elfinator84@yandex.ru
        EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
        EOL

          echo "Applying database migrations..."
          python manage.py migrate --settings=booking_system.settings.production

          echo "Collecting static files..."
          python manage.py collectstatic --noinput --settings=booking_system.settings.production

          echo "Deployment commands executed successfully."
        EOF
        echo "Commands executed on server."

    - name: Restart application
      run: |
        echo "Restarting application..."
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e
          set -x
          sudo systemctl restart gunicorn
          sudo systemctl reload nginx
        EOF
        echo "Application restarted."